### PR TITLE
@mzikherman => Bump version

### PR DESCRIPTION
**Pull request by l2succes**

### CODE REVIEW

**Comment by mzikherman** [comment]
Cool, is this all that's needed for https://github.com/artsy/force/pull/1262 to pull it in?

Also, weird ❌

**Comment by l2succes** [comment]
No after you change the version number and commit it to git.
You have to run `yarn prepublishOnly && npm publish` which will zip all the files in `dist` and upload it to npm

**Comment by mzikherman** [comment]
Question, how come https://github.com/artsy/reaction-force/pull/105 didn't fail with latest master on these specs? I thought it should, since after the previous merge that included this, shouldn't that PR needed to have been updated with latest (and then failed)?

**Comment by l2succes** [comment]
@mzikherman Yeah that's a good point. seems like the artwork component was in non-hovered state for the other PR and in hovered state for this PR. We should look into that to make sure the tests are deterministic.

**Comment by alloy** [comment]
You shouldn't need to run `yarn prepublishOnly`, maybe you need to update your npm?

**Pull request merged**
