### PR TITLE
Adds tslint and enforces rules

### PR DESCRIPTION
**Pull request by l2succes**
This PR adds tslint and tslint-react which is a linter for typescript and jsx in typescript files.

It also adds a pre-commit hook which will run `yarn run test` and `yarn run lint` before allowing a commit.

To fix linter issues, you can run `yarn lint -- --fix` which will fix a number of small errors (whitespace, etc...) but some errors must still be fixed manually.

It also adds a `yarn lint` as a command to run on Circle CI .

### CODE REVIEW

**Comment by alloy** [comment]
Good stuff.

Did you take the majority of the rules from Emission's config? If not, maybe do a comparison.

We definitely need to add the react config to Emission too, that seems useful 👍

**Comment by xtina-starr** [comment]
@l2succes @alloy yeah I was wondering where the rules came from as well. 

This definitely gives the project some structure and consistency. I like!

**Comment by yuki24** [comment]
:shipit: 👍

**Comment by xtina-starr** [comment]
Mergin'

**Comment by l2succes** [comment]
@alloy Na I wrote it from scratch but comparing it to the one in emission, the configs are almost the same except for a few rules so we can combine them pretty easily.

**Pull request merged**
