### PR TITLE
[dev] Make HMR work on /inquiries.

### PR DESCRIPTION
**Pull request by alloy**
Need to not only export the Relay container, but also the component itself.

See https://github.com/alloy/relational-theory/commit/2cc900ea216f61c7a4a8096bb9177a648b135129

### CODE REVIEW

**Comment by orta** [comment]
Is this something we should make  danger rule for in the future? In Emission there's some per-component based rules already

**Comment by alloy** [comment]
Ooh, yeah, I like that 👌

**Comment by l2succes** [comment]
@orta Would the rule just be export all React components by default?
I feel like it'd be too much work to check that component is wrapped in a Relay container somewhere

**Comment by orta** [comment]
it's code that doesn't exist yet, we can do whatever we want 👍

**Pull request merged**
