### PR TITLE
@orta => Add publishing / particle components

### PR DESCRIPTION
**Pull request by eessex**
Moves Particle2 components to components/publishing

Have a few q's...
- Is there an established way to provide fixtures or sample data for the storybook when not using relay
- How can the storybook file be broken into separate files by concern
- How to set up tests

### CODE REVIEW

**Comment by alloy** [comment]
@eessex Be sure to use the assign functionality so @orta gets a ping from the no-slacking bot.

**Comment by orta** [comment]
Alright, so for this, I'll give some examples from Emission, here's some PRs for additional context

- https://github.com/artsy/emission/pull/586


Let's look at a component from Emission, the ArtworkConsignmentToDo. It looks like this on the right:



Which has a bunch of different states. It's a PureComponent (so no state) so testing is very much a case of what props come in and what is the outcome.

Its Props are:

```ts
interface TODOProps extends ConsignmentSetup {
  goToArtist?: () => void
  goToPhotos?: () => void
  goToMetadata?: () => void
  goToLocation?: () => void
  goToProvenance?: () => void
}
```

and as it `extends` a `ConsignmentSetup`, I'll show that too:

```ts
export interface ConsignmentSetup {
  artist?: ArtistResult
  photos?: string[]
  metadata?: ConsignmentMetadata
  location?: string
  provenance?: string
}
```

( note: anything with a `?` means that it's optional, so basically everything on props for this component is optional, as it's all user-inputted data )

So I want to be testing a good chunk of the `Consignment` with different types of props. So in my story, I want to create a bunch of different props to test:

```ts
const withArtist: ConsignmentSetup = { artist: { name: "Glenn Brown", id: "gb", image: { url: "" } } }

const withOnePhoto: ConsignmentSetup = {
  ...withArtist,
  photos: ["https://d32dm0rphc51dk.cloudfront.net/VFiyokWNcBZNlfglZND_3g/small_square.jpg"],
}

const withPhotos: ConsignmentSetup = {
  ...withArtist,
  photos: [
    "https://d32dm0rphc51dk.cloudfront.net/VFiyokWNcBZNlfglZND_3g/small_square.jpg",
    "https://d32dm0rphc51dk.cloudfront.net/UivXcEE-GMQuBqBiHmvdcg/small_square.jpg",
  ],
}

const metadata: ConsignmentMetadata = {
  title: "My Work",
  year: "1983",
  category: "Design",
  materials: "Wood",
  width: 100,
  height: 100,
  depth: null,
  unit: "cm",
  displayString: "5/5",
}

const withMetadata: ConsignmentSetup = {
  ...withPhotos,
  metadata,
}

...
```

You can see it [fully here](https://github.com/artsy/emission/blob/22674ce5131f9407f4d3bce3a0043637952014ce/src/lib/components/consignments/__stories__/consignments-todo.story.tsx) - this is then passed into a series of stories via the `...` operator:

```tsx
storiesOf("Consignments - TODO")
  .add("Empty", () => <TODO />)
  .add("With Artist", () => <TODO {...withArtist} />)
  .add("With Photos", () => <TODO {...withPhotos} />)
  .add("With Metadata", () => <TODO {...withMetadata} />)
  .add("With Location", () => <TODO {...withLocation} />)
  .add("With Provenance", () => <TODO {...withProvenance} />)
  .add("With Just Metadata", () => <TODO metadata={metadata} />)
  .add("With One Photo", () => <TODO {...withOnePhoto} />)
  .add("With Long Provenance", () => <TODO provenance={longProv} />)
```

This strategy worked well, then I realised that I wanted to have tests that re-used these different props+component combos, and made them exportable for testing inside a snapshot.

Today, I make them all exportable as an array of names: state - [see here](https://github.com/artsy/emission/blob/master/src/lib/Components/Consignments/__stories__/Todo.story.tsx), this is then used by a test runner to create jest-snapshots.

```tsx
// Converts a set of state and a component type into a set of stories
const autoStories: AutoStory[] = [search, bottomAlignedButton, todo]

export const Wrapper = props =>
  <View style={{ flex: 1, backgroundColor: "black", padding: 20, marginTop: 60 }}>
    {props.children}
  </View>

// Allows stories to strictly be about their state and the
// component itself.

autoStories.forEach(storybook => {
  const stories = storiesOf(storybook.name)

  storybook.allStates.forEach(element => {
    const name = Object.keys(element)[0]
    stories.add(name, () =>
      <Wrapper>
        <storybook.component {...element[name]} />
      </Wrapper>
    )
  })
})
```

This pattern works well when you have a lot of different states to test. For something less, it's easier to test by just writing the props in normally. For example: [here](https://github.com/artsy/emission/blob/master/src/lib/Components/Consignments/__stories__/Style.story.tsx#L1). 

Testing for something simple like your icon, can be done by something like this:

```ts
import "react-native"

import * as React from "react"
import * as renderer from "react-test-renderer"

import Circle from "../circle_image"

it("renders properly", () => {
  const button = renderer.create(<Circle source={require("../../images/email.png")} />).toJSON()
  expect(button).toMatchSnapshot()
})
```

Which is a linter that the thing you have works as expected. Then there's some more complex tests that you can do (from an upcoming PR):

```tsx
import Artist from "../artist"

const emptyProps = { navigator: {} as any, route: {} as any }

describe("callbacks", () => {
  it("calls pop when done is tapped", () => {
    const navigator: any = { pop: jest.fn() }
    const artist = new Artist({ navigator, route: {} })
    artist.doneTapped()
    expect(navigator.pop).toHaveBeenCalled()
  })

  it("calls nav.pop & updateWithResult when a result is tapped", () => {
    const navigator: any = { pop: jest.fn() }
    const updateWithResult = jest.fn()
    const artist = new Artist({ navigator, route: {}, updateWithResult })

    artist.artistSelected({} as any)

    expect(navigator.pop).toHaveBeenCalled()
    expect(updateWithResult).toHaveBeenCalled()
  })
})

describe("state", () => {
  it("is set up with empty props", () => {
    const artist = new Artist(emptyProps)
    expect(artist.state).toEqual({ query: null, searching: false, results: null })
  })

  it("is set up with empty props", () => {
    const artist = new Artist(emptyProps)
    expect(artist.state).toEqual({ query: null, searching: false, results: null })
  })

  it("sets new state when text is changed", () => {
    const artist = new Artist(emptyProps)
    artist.setState = jest.fn()
    artist.searchForQuery = jest.fn()

    artist.textChanged("Blu")

    expect(artist.setState).toHaveBeenCalledWith({ query: "Blu", searching: true })
    expect(artist.searchForQuery).toHaveBeenCalledWith("Blu")
  })
})
```

**Comment by orta** [comment]
Yeah - this looks great to me 👍

**Comment by alloy** [comment]
Can’t wait to see the updated storybooks! 🚀

**Comment by eessex** [comment]
ok to merge?

**Comment by orta** [comment]
It was still marked as `[WIP]` - so if it's not, totally 👍

**Comment by orta** [comment]
before you go, can you write down the average time it takes for a save to appear in your storybooks? should be something like this:

```
[at-loader] Ok, 1.587 sec.
webpack built bfd815ee8e63de0c3b52 in 6654ms
```

in your terminal

**Comment by eessex** [comment]
Just realized I forgot to include an export in the components folder -- will take a look at the load time too.

**Comment by eessex** [comment]
Ok! This is ready to go now, my build times range between 1.3 - 2.8 sec,  usually closer to 2.2

**Comment by orta** [comment]
Thanks @eessex - let's do this ❤️

**Pull request merged**
