### PR TITLE
Remove links to signup page

### PR DESCRIPTION
**Pull request by yuki24**
We still don't have a signup page implemented yet.

### CODE REVIEW

**Comment by alloy** [comment]
Gotta update the snapshots!

**Comment by yuki24** [comment]
@alloy done!

**Comment by alloy** [comment]
Awww… You’ve been 👮’d!

**Comment by yuki24** [comment]
I ended up just deleting them instead of commenting to work around the lint check.

**Comment by alloy** [comment]
Hah. Works for me 👍

**Pull request merged**
