### PR TITLE
@l2succes - Updates main package to export components and apps

### PR DESCRIPTION
**Pull request by broskoski**
On the force side, we will want to be able to export individual client-side components as well as server-rendered apps. This makes changes to allow for both. 

I will update things on the force side so the loyalty app still works.

As a side note (just to open it up for discussion.....sorry for not catching this your original PR), I'm not _entirely_ sure that this repo is the best place for whole server applications like the loyalty apps. It could just be how I envisioned this repo taking shape, but I assumed that reaction-force is where we build the individual  reusable client-side components, and Force would be where they all come together. The fact that we are importing Backbone into this repo now feels a little off! Obviously this is totally open for debate, but just want to get your take here before we get too far down the rabbit hole.

### CODE REVIEW

**Comment by mzikherman** [comment]
I too thought (when we started), we'd be exporting components and still combining them into the page on Force (though I'm down to try either scenario).

I remember we sort of discussed this a little while ago, and decided to try to get the whole app built here, but I can't totally recall the nuances of the discussion. At least one complication is having to include artsy passport, etc. in order to replicate some of the Force stack's server-side abilities and middleware in this stack.

I don't have a strong opinion, but I'm down to re-open and participate in the discussion again if needed.

**Comment by l2succes** [comment]
I agree 100% to everything you just said @cab. I don't think this repo best place to put the loyalty program app or any app for that matter. Personally, I think we should make a `loyalty-program` repo/app which uses `reaction-force` and gets added as a dependency to force. Ideally `reaction-force` would stay a library of components to build apps from and import that. 

Part of the reason loyalty app ended up in reaction-force instead of force was because of all the new dev tools that are introduced in this repo (typescript, fuse-box, styled-components). We wanted to test this setup in a contained environment and didn't want to have to deal with three repos right from the start of the project.

If we all agree on this I'd be happy to move apps into their own repos.

**Comment by broskoski** [comment]
So as a practical for instance, currently I want to replace the client-side code on the tag page ( https://www.artsy.net/tag/balloon ) with the new `ArtworkFilter`. This shouldn't necessarily require me to recreate the navigation bar, notifications, dropdowns, search, recently viewed artworks, etc.

**Comment by broskoski** [comment]
Ah, jumped the gun on that comment! Cool yes, totally in agreement :)

**Comment by broskoski** [comment]
Personally, I would just pull the app together in Force's current setup (to avoid having to deal with any weirdness that might arise from having two versions of `artsy-passport` running (though maybe you already have that figured out?). But that's just lazy ol' me.

**Comment by l2succes** [comment]
Yes I thought about that but I already figured out how to make a sub `artsy-passport` work within force.

Also, the idea behind having loyalty program app in a separate repo is also to move away from monolithic force and break sub-apps into smaller maintainable modules. But we'll see what works best.

**Comment by l2succes** [comment]
In terms of the PR, it looks good. 

I'd say just remove all the `dist` compiled js files as we're not gonna check in that folder anymore.

**Comment by broskoski** [comment]
@l2succes how will that work? Where should I point the main file in `package.json` in that case?

**Comment by l2succes** [comment]
You can still point the main file to `dist/index.js`. It just won't be included in source control anymore. To make this work, we have to create an [.npmignore](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) file which doesn't include `dist`. That way it'll get included in the npm package but not in source control. 

Then we can call `yarn publish` when we want to update the package.
The first version is published on npm already (https://www.npmjs.com/package/@artsy/reaction-force)

**Comment by broskoski** [comment]
Wait, we actually want to put dist in .gitignore, not .npmignore right? We want the dist folder in the package but not in the repo.

**Comment by l2succes** [comment]
@broskoski yup exactly

**Comment by broskoski** [comment]
Cool, mergin!

**Comment by alloy** [comment]
> I too thought (when we started), we'd be exporting components and still combining them into the page on Force (though I'm down to try either scenario).

That was the plan for the artwork bricks that @broskoski is working on.

>  I don't think this repo best place to put the loyalty program app or any app for that matter. Personally, I think we should make a loyalty-program repo/app which uses reaction-force and gets added as a dependency to force. Ideally reaction-force would stay a library of components to build apps from and import that.

While I don’t have a problem with 1 package (and repo) that exports both components and apps, I’m not entirely opposed to having separate packages for components and apps.

Keep in mind that often having more repos can be a bit of drag during rapid development, though, so I’d definitely prefer not to have a repo/package per app.

**Pull request merged**
